import { PageAnnotation } from './types'

export const homepageAnnotations: PageAnnotation = {
  pageId: 'homepage',
  pageName: 'Homepage',
  pageNameTh: 'หน้าแรก',
  path: '/',
  lastUpdated: '2026-04-28',
  version: '1.0.0',
  elements: [
    {
      id: 'hero-section',
      selector: 'section[data-doc="hero-section"]',
      name: 'Hero Section',
      nameTh: 'ส่วนแบนเนอร์หลัก',
      type: 'hero',
      description: 'Full-width hero banner with background image, headline, and CTA buttons',
      descriptionTh: 'แบนเนอร์เต็มหน้าจอพร้อมภาพพื้นหลัง หัวข้อ และปุ่มเรียกร้องให้ดำเนินการ',
      component: 'HeroSection',
      status: 'active',
      ux: {
        goal: 'First impression & conversion',
        kpi: 'CTR on CTA buttons',
        priority: 5,
      },
      technical: {
        cssSelector: 'section.relative.min-h-screen',
        dataSource: 'static',
        responsive: { desktop: true, tablet: true, mobile: true },
        tailwindClasses: ['relative', 'min-h-screen', 'flex', 'items-center'],
      },
      behavior: {
        route: '/',
        eventName: 'hero_view',
      },
      accessibility: {
        role: 'banner',
        ariaLabel: 'Hero banner section',
      },
    },
    {
      id: 'hero-cta-primary',
      selector: '[data-doc="hero-cta-primary"]',
      name: 'Primary CTA Button',
      nameTh: 'ปุ่มหลัก',
      type: 'button',
      description: 'Main conversion button that navigates to villas listing page',
      descriptionTh: 'ปุ่มหลักสำหรับนำทางไปยังหน้ารายการวิลล่า',
      textContent: 'Explore Villas',
      component: 'ButtonPrimary',
      variant: 'large-red',
      status: 'active',
      ux: {
        goal: 'Drive villa page visits',
        kpi: 'Click-through rate',
        priority: 5,
      },
      technical: {
        cssSelector: 'a[data-doc="hero-cta-primary"]',
        dataSource: 'static',
        responsive: { desktop: true, tablet: true, mobile: true },
        tailwindClasses: ['bg-red-600', 'text-white', 'px-8', 'py-4', 'rounded-lg'],
      },
      behavior: {
        clickAction: 'navigate',
        route: '/villas',
        eventName: 'hero_cta_click',
      },
      accessibility: {
        ariaLabel: 'Explore our luxury villas',
        role: 'link',
      },
    },
    {
      id: 'hero-headline',
      selector: '[data-doc="hero-headline"]',
      name: 'Hero Headline',
      nameTh: 'พาดหัวหลัก',
      type: 'heading',
      description: 'Main H1 headline with brand name and tagline',
      descriptionTh: 'พาดหัว H1 พร้อมชื่อแบรนด์และคำขวัญ',
      textContent: 'NUCHA VILLA — Luxury Living in Pattaya',
      component: 'HeroTitle',
      status: 'active',
      ux: {
        goal: 'Brand recognition & emotional connection',
        priority: 5,
      },
      technical: {
        cssSelector: 'h1[data-doc="hero-headline"]',
        dataSource: 'static',
        responsive: { desktop: true, tablet: true, mobile: true },
        tailwindClasses: ['text-5xl', 'font-bold', 'text-white', 'drop-shadow'],
      },
      accessibility: {
        role: 'heading',
        ariaLabel: 'Main page headline',
      },
    },
    {
      id: 'nav-logo',
      selector: '[data-doc="nav-logo"]',
      name: 'Navigation Logo',
      nameTh: 'โลโก้นำทาง',
      type: 'image',
      description: 'Brand logo in navigation bar, links to homepage',
      descriptionTh: 'โลโก้แบรนด์ในแถบนำทาง ลิงก์ไปหน้าแรก',
      component: 'BrandLogo',
      status: 'active',
      ux: {
        goal: 'Brand identity & navigation anchor',
        priority: 4,
      },
      technical: {
        cssSelector: 'a[data-doc="nav-logo"] img',
        dataSource: 'static',
        responsive: { desktop: true, tablet: true, mobile: true },
      },
      behavior: {
        clickAction: 'navigate',
        route: '/',
      },
      accessibility: {
        ariaLabel: 'Nucha Villa logo - go to homepage',
      },
    },
    {
      id: 'services-section',
      selector: 'section[data-doc="services-section"]',
      name: 'Services Section',
      nameTh: 'ส่วนบริการ',
      type: 'section',
      description: 'Showcase of company services with accordion-style cards',
      descriptionTh: 'แสดงบริการต่างๆ ด้วยการ์ดแบบแอคคอร์เดียน',
      component: 'ServicesSection',
      status: 'active',
      ux: {
        goal: 'Inform visitors about services',
        priority: 4,
      },
      technical: {
        cssSelector: 'section[data-doc="services-section"]',
        dataSource: 'api',
        responsive: { desktop: true, tablet: true, mobile: true },
      },
      behavior: {
        eventName: 'services_section_view',
      },
    },
    {
      id: 'portfolio-grid',
      selector: '[data-doc="portfolio-grid"]',
      name: 'Portfolio Grid',
      nameTh: 'กริดผลงาน',
      type: 'section',
      description: 'Grid display of portfolio/villa projects with hover effects',
      descriptionTh: 'แสดงผลงาน/โครงการวิลล่าแบบกริดพร้อมเอฟเฟกต์ hover',
      component: 'PortfolioGrid',
      status: 'active',
      ux: {
        goal: 'Showcase projects & drive detail views',
        kpi: 'Project detail page visits',
        priority: 4,
      },
      technical: {
        cssSelector: 'div[data-doc="portfolio-grid"]',
        dataSource: 'api',
        responsive: { desktop: true, tablet: true, mobile: true },
      },
    },
    {
      id: 'contact-button',
      selector: '[data-doc="contact-button"]',
      name: 'Contact Button',
      nameTh: 'ปุ่มติดต่อ',
      type: 'button',
      description: 'Floating or fixed contact button that opens WhatsApp/Line',
      descriptionTh: 'ปุ่มติดต่อแบบลอย/ติด เปิด WhatsApp/Line',
      textContent: 'Contact Us',
      component: 'ContactButton',
      variant: 'floating',
      status: 'active',
      ux: {
        goal: 'Maximize contact conversion',
        kpi: 'Contact initiated',
        priority: 5,
      },
      technical: {
        cssSelector: 'button[data-doc="contact-button"]',
        dataSource: 'env',
        responsive: { desktop: true, tablet: true, mobile: true },
      },
      behavior: {
        clickAction: 'open_external',
        externalUrl: 'https://wa.me/...',
        eventName: 'contact_click',
      },
    },
  ],
}

export const allPageAnnotations: PageAnnotation[] = [homepageAnnotations]

export const pageList = allPageAnnotations.map((p) => ({
  pageId: p.pageId,
  pageName: p.pageName,
  pageNameTh: p.pageNameTh,
  path: p.path,
  elementCount: p.elements.length,
}))
